baseURL = "https://pwnedtech.org/"
languageCode = "en-us"
paginate = 5
theme = "portio"
title = "PwnedTech"
# Main Menu
[[menu.main]]
name = "Inicio"
url = "#home"
weight = 1
[[menu.main]]
name = "Información"
url = "#about"
weight = 2
[[menu.main]]
name = "Contacto"
url = "#contact"
weight = 3

# Sitemap Menu
[[menu.sitemap]]
name = "Información"
url = "about"
weight = 1
#[[menu.sitemap]]
#name = "Frequently Ask Question"
#url = "#"
#weight = 2
#[[menu.sitemap]]
#name = "Privacy & Policy"
#url = "#"
#weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 2

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

#[params.address]
#address = "23 Khan Niketon, Grand Street, NYK."
#email = "hello@example.com"
#openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
#phone = "+(448) 833 5272 332"

#[params.map]
#APIkey = "YOUR GOOGLE MAP API"
#latitude = "23.7783741"
#longitude = "90.3746808"
#pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/pwnedtech"
weight = 1
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/pwnedtech"
weight = 1
